### ISSUE TITLE
Use site.webmanifest instead of manifest.json

### ISSUE THREAD

**Issue by filips123** [jfadev/jfa-pwa-toolkit#1]
Use `site.webmanifest` instead of `manifest.json`.

Although it is not required, it is [reccomended by W3C](https://w3c.github.io/manifest/#media-type-registration) that manifest uses ` application/manifest+json` media type and `.webmanifest ` extension.

**Comment by jfadev** [comment]
I will review this to include it in the next update. @filips123 Thank you.

**Comment by jfadev** [comment]
It has been suggested the possibility to rename the file `manifest.json` by `app.webmanifest` in the [documentation](https://github.com/jfadev/jfa-pwa-toolkit/blob/master/README.md)
